#!/bin/sh
# open folder
APP_PATH="/Users/$USER/Desktop/"
APP_FOLDER=$APP_PATH'crowdsourcing'
BLAZEGRAPH_DATA_PATH="./"

# activate virtualenv
cd $APP_FOLDER
# activate virtualenv
source $APP_FOLDER/bin/activate
# launch blazegraph
lsof -ti tcp:3000 | xargs kill
java -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -server -Xmx2g -Djetty.port=3000 -Dbigdata.propertyFile=blaze.properties -jar blazegraph.jar &
# launch app
sleep 3
lsof -ti tcp:8080 | xargs kill
python3 app.py 8080
# kill everything when exiting terminal
trap 'kill $(ps -o pid= --ppid $$) 2>/dev/null' exit
